FROM jenkins/jenkins:lts-jdk21

USER  root

RUN apt-get update && apt-get install -y \
    python3 \
    python3-venv \
    python3-pip \
    docker.io \
    curl \
    && rm -rf /var/lib/apt/lists/* \
    && usermod -aG docker jenkins

USER jenkins


